<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\CH32UpperComputer.Core\CH32UpperComputer.Core.csproj" />
    <ProjectReference Include="..\..\src\CH32UpperComputer.Infrastructure\CH32UpperComputer.Infrastructure.csproj" />
  </ItemGroup>

</Project>
