<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CH32UpperComputer.Core\CH32UpperComputer.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.IO.Ports" />
  </ItemGroup>

</Project>
