<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <AssemblyName>CKAPP</AssemblyName>
    <ApplicationIcon>Assets\CKAPP.ico</ApplicationIcon>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SelfContained>true</SelfContained>
    <PublishSingleFile>true</PublishSingleFile>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
    <PublishTrimmed>false</PublishTrimmed>
    <PublishDocumentationFiles>false</PublishDocumentationFiles>
    <DebugType>embedded</DebugType>
    <InvariantGlobalization>false</InvariantGlobalization>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CH32UpperComputer.Core\CH32UpperComputer.Core.csproj" />
    <ProjectReference Include="..\CH32UpperComputer.Infrastructure\CH32UpperComputer.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\InkPlumReference.jpg" />
  </ItemGroup>

</Project>
